python -B finetune_simple.py \
--config cifar10.yml \
--timesteps 100 \
--eta 0 \
--ni \
--exp run/finetune_simple_v2/cifar10_ours_T=$1_lr$2_beta$3.pth \
--doc post_training \
--skip_type quad  \
--pruning_ratio 0.3 \
--use_ema \
--use_pretrained \
--thr $1 \
--pruner ours \
--lr $2 \
--beta1 $3 \