python -B finetune_simple.py \
--config cifar10.yml \
--timesteps 100 \
--eta 0 \
--ni \
--exp run/finetune_simple_v2/$3$2 \
--doc post_training \
--skip_type quad  \
--use_ema \
--restore_from "$4" \
--depth_method kim24layermerge \
--depth_path $2 \
--thr $1 \
--lr 0.0004 \
--from_pruned